CREATE DATABASE [Service]
GO

USE [Service]
GO

CREATE TABLE Users
(Id INT IDENTITY,
Username VARCHAR(30) UNIQUE NOT NULL,
[Password] VARCHAR(50) NOT NULL,
[Name] VARCHAR(50),
Birthdate DATETIME,
Age INT,
Email VARCHAR(50) NOT NULL,

CONSTRAINT PK_Users_Id
PRIMARY KEY(Id),
CONSTRAINT check_ageValue
CHECK (Age BETWEEN 14 AND 110))
GO

CREATE TABLE Departments
(Id INT IDENTITY,
[Name] VARCHAR(50) NOT NULL

CONSTRAINT PK_Departments_Id
PRIMARY KEY(Id))
GO

CREATE TABLE Employees
(Id INT IDENTITY,
FirstName VARCHAR(25),
LastName  VARCHAR(25),
Birthdate DATETIME,
Age INT,
DepartmentId INT

CONSTRAINT PK_Employees_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Employees_DepartmentId
FOREIGN KEY (DepartmentId)
REFERENCES Departments(Id),

CONSTRAINT check_ageValueEmployees
CHECK (Age BETWEEN 18 AND 110))
GO

CREATE TABLE Categories
(Id INT IDENTITY,
[Name] VARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL

CONSTRAINT PK_Categories_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Categories_DepartmentId
FOREIGN KEY (DepartmentId)
REFERENCES Departments(Id))
GO

CREATE TABLE [Status]
(Id INT IDENTITY,
[Label] VARCHAR(30) NOT NULL,

CONSTRAINT PK_Status_Id
PRIMARY KEY(Id))
GO

CREATE TABLE Reports
(Id INT IDENTITY,
CategoryId INT NOT NULL,
StatusId INT NOT NULL,
OpenDate DATETIME NOT NULL,
CloseDate DATETIME,
[Description] VARCHAR(200) NOT NULL,
UserId INT NOT NULL,
EmployeeId INT

CONSTRAINT PK_Reports_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Reports_CategoryId
FOREIGN KEY (CategoryId)
REFERENCES Categories(Id),
CONSTRAINT FK_Reports_StatusId
FOREIGN KEY (StatusId)
REFERENCES Status(Id),
CONSTRAINT FK_Reports_UserId
FOREIGN KEY (UserId)
REFERENCES Users(Id),
CONSTRAINT FK_Reports_EmployeeId
FOREIGN KEY (EmployeeId)
REFERENCES Employees(Id))
GO
