CREATE DATABASE School
GO

USE School
GO

CREATE TABLE Students
(Id INT IDENTITY,
FirstName NVARCHAR(30) NOT NULL,
MiddleName NVARCHAR(25),
LastName NVARCHAR(30) NOT NULL,
Age INT NOT NULL,
Address NVARCHAR(50),
Phone NCHAR(10),

CONSTRAINT PK_Students_Id
PRIMARY KEY(Id),
CONSTRAINT check_ageValue
CHECK (Age > 0))
GO

CREATE TABLE Subjects
(Id INT IDENTITY,
Name NVARCHAR(20) NOT NULL,
Lessons INT NOT NULL

CONSTRAINT PK_Subjects_Id
PRIMARY KEY(Id)
CONSTRAINT check_LessonsValue
CHECK (Lessons > 0))
GO

CREATE TABLE StudentsSubjects
(Id INT IDENTITY,
StudentId INT NOT NULL,
SubjectId INT NOT NULL,
Grade DECIMAL(5,2) NOT NULL

CONSTRAINT PK_StudentsSubjects_Id
PRIMARY KEY(Id)
CONSTRAINT FK_StudentsSubjects_StudentId
FOREIGN KEY (StudentId)
REFERENCES Students(Id),
CONSTRAINT FK_StudentsSubjects_SubjectId
FOREIGN KEY (SubjectId)
REFERENCES Subjects(Id),

CONSTRAINT check_GradeValue
CHECK (Grade BETWEEN 2 AND 6))
GO

CREATE TABLE Exams
(Id INT IDENTITY,
Date DATETIME,
SubjectId INT NOT NULL

CONSTRAINT PK_Exams_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Exams_SubjectId
FOREIGN KEY (SubjectId)
REFERENCES Subjects(Id))
GO

CREATE TABLE StudentsExams
(StudentId INT NOT NULL,
ExamId INT NOT NULL,
Grade DECIMAL(5,2) NOT NULL

CONSTRAINT PK_StudentsExams_StudentId_ExamId
PRIMARY KEY(StudentId,ExamId)
CONSTRAINT FK_StudentsExams_StudentId
FOREIGN KEY (StudentId)
REFERENCES Students(Id),
CONSTRAINT FK_StudentsExams_ExamId
FOREIGN KEY (ExamId)
REFERENCES Exams(Id),

CONSTRAINT check_GradeValueStudentsExams
CHECK (Grade BETWEEN 2 AND 6))
GO

CREATE TABLE Teachers
(Id INT IDENTITY,
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(20) NOT NULL,
Address NVARCHAR(20) NOT NULL,
Phone CHAR(10),
SubjectId INT NOT NULL

CONSTRAINT PK_Teachers_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Teachers_SubjectId
FOREIGN KEY (SubjectId)
REFERENCES Subjects(Id))
GO

CREATE TABLE StudentsTeachers
(StudentId INT NOT NULL,
TeacherId INT NOT NULL

CONSTRAINT PK_StudentsTeachers_StudentId_TeacherId
PRIMARY KEY(StudentId,TeacherId)
CONSTRAINT FK_StudentsTeachers_StudentId
FOREIGN KEY (StudentId)
REFERENCES Students(Id),
CONSTRAINT FK_StudentsTeachers_TeacherId
FOREIGN KEY (TeacherId)
REFERENCES Teachers(Id))
GO