CREATE DATABASE Airport
GO

USE Airport
GO

CREATE TABLE Planes
(Id INT IDENTITY,
[Name] VARCHAR(30) NOT NULL,
Seats INT NOT NULL, 
[Range] INT NOT NULL

CONSTRAINT PK_Planes_Id
PRIMARY KEY(Id))
GO

CREATE TABLE Flights
(Id INT IDENTITY,
DepartureTime DATETIME, 
ArrivalTime DATETIME, 
Origin VARCHAR(50) NOT NULL,
Destination VARCHAR(50) NOT NULL,
PlaneId INT NOT NULL

CONSTRAINT PK_Flights_Id
PRIMARY KEY(Id)
CONSTRAINT FK_Flights_PlaneId
FOREIGN KEY(PlaneId)
REFERENCES Planes(Id))
GO

CREATE TABLE Passengers
(Id INT IDENTITY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Age INT NOT NULL,
[Address] VARCHAR(30) NOT NULL,
PassportId CHAR(11)	NOT NULL

CONSTRAINT PK_Passengers_Id
PRIMARY KEY(Id))
GO

CREATE TABLE LuggageTypes
(Id INT IDENTITY,
[Type] VARCHAR(30) NOT NULL

CONSTRAINT PK_LuggageTypes_Id
PRIMARY KEY(Id))
GO

CREATE TABLE Luggages
(Id INT IDENTITY,
LuggageTypeId INT NOT NULL, 
PassengerId INT NOT NULL

CONSTRAINT PK_Luggages_Id
PRIMARY KEY(Id),
CONSTRAINT FK_Luggages_LuggageTypeId
FOREIGN KEY(LuggageTypeId)
REFERENCES LuggageTypes(Id),
CONSTRAINT FK_Luggages_PassengerId
FOREIGN KEY(PassengerId)
REFERENCES Passengers(Id))
GO

CREATE TABLE Tickets
(Id INT IDENTITY,
PassengerId INT NOT NULL, 
FlightId INT NOT NULL,
LuggageId INT NOT NULL,
Price DECIMAL(15,2) NOT NULL

CONSTRAINT PK_Tickets_Id
PRIMARY KEY(Id),
CONSTRAINT FK_Tickets_PassångerId
FOREIGN KEY(PassengerId)
REFERENCES Passengers(Id),
CONSTRAINT FK_Tickets_FlightId
FOREIGN KEY(FlightId)
REFERENCES Flights(Id),
CONSTRAINT FK_Tickets_LuggageId
FOREIGN KEY(LuggageId)
REFERENCES Luggages(Id))
GO