CREATE DATABASE OnlineStore

use OnlineStore

CREATE TABLE Cities(
CityID INT NOT NULL,
[Name] NVARCHAR(50)

CONSTRAINT PK_Cities_CityID
 PRIMARY KEY (CityID))

 CREATE TABLE Customers(
CustomerID INT NOT NULL,
[Name] NVARCHAR(50),
Birthday DATE,
CityID INT NOT NULL

CONSTRAINT PK_Customers_CustomerID
 PRIMARY KEY (CustomerID)
 CONSTRAINT FK_City_Customer
 FOREIGN KEY (CityID)
 REFERENCES Cities(CityID))
  
  CREATE TABLE Orders(
OrderID INT NOT NULL,
CustomerID INT NOT NULL

CONSTRAINT PK_Orders_OrderID
 PRIMARY KEY (OrderID)
 CONSTRAINT FK_Customer_Order
 FOREIGN KEY (CustomerID)
 REFERENCES Customers(CustomerID))

 CREATE TABLE ItemTypes(
ItemTypeID INT NOT NULL,
[Name] NVARCHAR(50)

CONSTRAINT PK_ItemTypes_ItemTypeID
 PRIMARY KEY (ItemTypeID))

  CREATE TABLE Items(
ItemID INT NOT NULL,
[Name] NVARCHAR(50),
ItemTypeID INT NOT NULL

CONSTRAINT PK_Items_ItemID
 PRIMARY KEY (ItemID)
  CONSTRAINT FK_ItemType_Item
 FOREIGN KEY (ItemTypeID)
 REFERENCES ItemTypes(ItemTypeID))

 CREATE TABLE OrderItems(
OrderID INT NOT NULL,
ItemID INT NOT NULL

CONSTRAINT PK_OrderItems_OrderID_ItemID 
 PRIMARY KEY (OrderID, ItemID)
  CONSTRAINT FK_OrderItems_Item
 FOREIGN KEY (ItemID)
 REFERENCES Items(ItemID),
   CONSTRAINT FK_OrderItems_Order
 FOREIGN KEY (OrderID)
 REFERENCES Orders(OrderID))

